name: music
description: "Made with ♥ by PuzzleTak"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # language
  flutter_localizations:
    sdk: flutter
  # packages
  flutter_bloc: ^9.1.0

  #icons
  cupertino_icons: ^1.0.8
  eva_icons_flutter: ^3.1.0
  flutter_feather_icons: ^2.0.0+1
  material_design_icons_flutter: ^7.0.7296

  # router
  go_router: ^14.8.1

  # animation
  flutter_animate: ^4.5.2
  animations: ^2.0.11

  # storage
  shared_preferences: ^2.5.3

  # request api
  http: ^1.3.0
  dio: ^5.8.0+1

  #music
  audio_service: ^0.18.18
  just_audio: ^0.10.0

  # widgets
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.12
  syncfusion_flutter_charts: ^28.1.41
  flutter_stepindicator: ^0.1.7
  dotted_border: ^2.0.0

  # util
  url_launcher: ^6.3.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jiffy: ^6.3.2
  dart_jsonwebtoken: ^2.17.0
  path_provider: ^2.1.5

  # permission
  permission_handler: ^11.4.0

  #info device
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  #notification
  flutter_local_notifications: ^19.0.0
  shamsi_date: ^1.0.4
  flutter_gen: ^5.10.0
  jhijri: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  # package for development
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: DiodrumArabic
      fonts:
        - asset: assets/fonts/DiodrumArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/DiodrumArabic-Extralight.ttf
          weight: 200
        - asset: assets/fonts/DiodrumArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/DiodrumArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/DiodrumArabic-Semibold.ttf
          weight: 600
        - asset: assets/fonts/DiodrumArabic-Bold.ttf
          weight: 700



flutter_gen:
  output: lib/gen/

